name: mysaasa_core_web
description: Core tools for the web-flutter
version: 0.0.1
author: Adam Hammer
homepage: https://www.mysaasa.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  mysaasa_core:
    path: ../mysaasa_core
  flutter_web: any
  flutter_web_ui: any
  provider:
    git:
      url: https://github.com/ahammer/provider


dependency_overrides:
  flutter_web:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web
  flutter_web_ui:
    git:
      url: https://github.com/flutter/flutter_web
      path: packages/flutter_web_ui

