name: mysaasa_core
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
#  flutter:
#    sdk: flutter
#  flutter_redux: ^0.5.3
  redux: ^3.0.0
#  provider: ^2.0.1
  built_value: ^6.5.0
#  flutter_redux_navigation: ^0.4.1
  
dev_dependencies:

  build_runner: ^1.4.0
  built_value_generator: ^6.5.0
  #//pedantic: ^1.4.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec
